#!/bin/bash
# Test the interactive trainer

echo "======================================================================="
echo "TESTING LATIN-TRAIN INTERACTIVE TRAINER"
echo "======================================================================="
echo ""
echo "This will launch the interactive trainer."
echo "You'll practice identifying grammar for 5 sentences."
echo ""
echo "Keyboard commands:"
echo "  j/k         - next/previous word"
echo "  Ctrl-1..9   - jump directly to word [1], [2], etc."
echo "  Backspace   - clear current word's input and start over"
echo "  n           - NOUN"
echo "  v           - VERB"
echo "  a           - ADJECTIVE"
echo "  p           - PREPOSITION"
echo "  1-5         - declension (after noun/adj)"
echo "  n/g/d/a/b/v - case (nominative/genitive/dative/accusative/ablative/vocative)"
echo "  p/i/f/r     - tense ([p]resent, [i]mperfect, [f]uture, pe[r]fect)"
echo "  Enter       - check answers, then advance to next sentence"
echo "  q           - quit"
echo ""
echo "Example: For 'Puella' (girl, nominative):"
echo "  Type: n 1 n Enter"
echo "        │ │ │"
echo "        │ │ └─ nominative case"
echo "        │ └─── 1st declension"
echo "        └───── NOUN"
echo ""
echo "Example: For 'ambulat' (walks, present):"
echo "  Type: v p Enter"
echo "        │ │"
echo "        │ └─ present tense"
echo "        └─── VERB"
echo ""
echo "Your attempts will be saved to: progress/my_attempts.jsonl"
echo ""
read -p "Press Enter to start trainer..."

cd /home/ivanadamin/spawn-solutions/research/1.140-classical-language-libraries/03-cli-utilities

bin/latin-train corpus/sample_parsed.jsonl --output progress/my_attempts.jsonl --user ivan

echo ""
echo "======================================================================="
echo "Trainer finished! Results saved."
echo "======================================================================="
echo ""
echo "View your results:"
echo "  bin/latin-analyze progress/my_attempts.jsonl"
echo ""
echo "View your mistakes:"
echo "  bin/latin-analyze progress/my_attempts.jsonl --mistakes"
echo ""
