const sidebars = {
  surveySidebar: [
    {type: "doc", id: "survey/survey-intro"},
    {type: "doc", id: "survey/1-001"},
    {type: "doc", id: "survey/1-002"},
    {type: "doc", id: "survey/1-003"},
    {type: "doc", id: "survey/1-004"},
    {type: "doc", id: "survey/1-005"},
    {type: "doc", id: "survey/1-010"},
    {type: "doc", id: "survey/1-022"},
    {type: "doc", id: "survey/1-033-1"},
    {type: "doc", id: "survey/1-033-2"},
    {type: "doc", id: "survey/1-033"},
    {type: "doc", id: "survey/1-034"},
    {type: "doc", id: "survey/1-039"},
    {type: "doc", id: "survey/1-040"},
    {type: "doc", id: "survey/1-042"},
    {type: "doc", id: "survey/1-043-1"},
    {type: "doc", id: "survey/1-047"},
    {type: "doc", id: "survey/1-049-1"},
    {type: "doc", id: "survey/1-050"},
    {type: "doc", id: "survey/1-055"},
    {type: "doc", id: "survey/1-056"},
    {type: "doc", id: "survey/1-060"},
    {type: "doc", id: "survey/1-061"},
    {type: "doc", id: "survey/1-063"},
    {type: "doc", id: "survey/1-071"},
    {type: "doc", id: "survey/1-073"},
    {type: "doc", id: "survey/1-074"},
    {type: "doc", id: "survey/1-080-1"},
    {type: "doc", id: "survey/1-080"},
    {type: "doc", id: "survey/1-091-2"},
    {type: "doc", id: "survey/1-094"},
    {type: "doc", id: "survey/1-096"},
    {type: "doc", id: "survey/1-100"},
    {type: "doc", id: "survey/1-104-1"},
    {type: "doc", id: "survey/1-110"},
    {type: "doc", id: "survey/1-120"},
    {type: "doc", id: "survey/1-122"},
    {type: "doc", id: "survey/1-127"},
    {type: "doc", id: "survey/1-130"},
    {type: "doc", id: "survey/1-131"},
    {type: "doc", id: "survey/1-140"},
    {type: "doc", id: "survey/1-141"},
    {type: "doc", id: "survey/1-142"},
    {type: "doc", id: "survey/1-148"},
    {type: "doc", id: "survey/1-160"},
    {type: "doc", id: "survey/1-164"},
    {type: "doc", id: "survey/1-200"},
    {type: "doc", id: "survey/replication"},
  ],
};

export default sidebars;
