# 3.503: HRIS/HCM Platforms - Experiment Metadata

experiment:
  id: "3.503"
  title: "HRIS/HCM Platforms"
  category: "Business Platforms"
  tier: 3
  status: "in_progress"
  started: "2025-10-31"
  completed: null

trigger:
  source: "CFO LinkedIn Community Forum Post"
  date: "2025-10-31"
  description: "Oracle HCM → Paycom migration question for 2000-employee organization"
  validation: "Real market need, high-value decision"

scope:
  domain: "HRIS/HCM"
  definition: "Human Resources Information Systems and Human Capital Management platforms"
  includes:
    - "Payroll processing and tax filing"
    - "Benefits administration"
    - "Time and attendance tracking"
    - "Recruiting and applicant tracking"
    - "Performance management"
    - "Learning management"
    - "HR analytics and reporting"
  excludes:
    - "Pure ATS without HRIS features"
    - "Standalone LMS products"
    - "Background check services only"
    - "Benefits brokers without technology platform"

platforms:
  startup_smb:
    - "Rippling"
    - "Gusto"
    - "Justworks"
    - "BambooHR"
    - "Paycor"
    - "Namely"
  mid_market:
    - "Paycom"
    - "ADP Workforce Now"
    - "Paylocity"
    - "UKG Pro"
  enterprise:
    - "Workday HCM"
    - "Oracle HCM Cloud"
    - "SAP SuccessFactors"
    - "ADP Vantage"
  time_specialists:
    - "UKG Dimensions"
    - "Deputy"
    - "When I Work"
  global:
    - "Deel"
    - "Oyster"
    - "Remote"
    - "Papaya Global"

research_questions:
  primary:
    - "When to use HRIS vs PEO vs Payroll-only service?"
    - "How to migrate from Oracle HCM? (2000+ employee scale)"
    - "What integration architecture is needed? (accounting, FP&A, time tracking)"
    - "Build vs buy decision framework?"
    - "Employee count graduation triggers?"
  secondary:
    - "AI capabilities (conversational HR, turnover prediction, resume parsing)"
    - "Single-platform vs best-of-breed approach?"
    - "Implementation complexity and payroll cutover strategies?"
    - "Multi-state and international compliance?"
    - "Cost structure and hidden fees?"

mpse_stages:
  s1_rapid:
    status: "in_progress"
    goal: "Quick platform overviews, 8 platforms"
    platforms: 8
    time_estimate: "3-5 days"
    deliverables:
      - "approach.md"
      - "rippling.md"
      - "gusto.md"
      - "bamboohr.md"
      - "paycom.md"
      - "adp-workforce-now.md"
      - "paylocity.md"
      - "workday-hcm.md"
      - "oracle-hcm-cloud.md"
      - "recommendations.md"

  s2_comprehensive:
    status: "not_started"
    goal: "Feature matrix, pricing, integrations, AI capabilities"
    time_estimate: "1-2 weeks"
    deliverables:
      - "approach.md"
      - "feature-matrix.md"
      - "integrations.md"
      - "pricing-tco.md"
      - "implementation-complexity.md"
      - "ai-capabilities-coverage.md"
      - "synthesis.md"

  s3_need_driven:
    status: "not_started"
    goal: "3 business scenarios with recommendations"
    scenarios: 3
    time_estimate: "3-5 days"
    deliverables:
      - "approach.md"
      - "tech-startup-10-50.md"
      - "growing-business-50-250.md"
      - "enterprise-migration-2000plus.md"
      - "synthesis.md"

  s4_strategic:
    status: "not_started"
    goal: "Frameworks, vendor viability, 5-year AI outlook"
    time_estimate: "3-5 days"
    deliverables:
      - "approach.md"
      - "graduation-frameworks.md"
      - "peo-vs-hris.md"
      - "vendor-viability.md"
      - "synthesis.md"

integration:
  upstream:
    - experiment: "3.006"
      title: "Accounting Software"
      relationship: "HRIS integrates with accounting for payroll journal entries"
    - experiment: "3.007"
      title: "FP&A Platforms"
      relationship: "HRIS provides headcount data to FP&A tools"

  downstream:
    - experiment: "3.008"
      title: "AP Automation"
      relationship: "Expense management connects to HRIS employee data"
    - experiment: "3.504"
      title: "Performance Management"
      relationship: "Standalone tools vs HRIS-native performance features"

success_criteria:
  s1_complete: "8 platform profiles exist"
  s2_complete: "Feature matrix covers 100+ features, pricing data complete"
  s3_complete: "3 scenarios have recommendations"
  s4_complete: "Decision frameworks answer graduation and build-vs-buy questions"
  full_complete: "CFO can use research to make confident HRIS selection"

business_value:
  market_size: "Every company 10+ employees"
  decision_frequency: "Every 5-7 years"
  annual_spend: "$50K-$500K depending on company size"
  consulting_opportunity: "$5K-$15K per HRIS selection project"
  query_value: "$200 per platform recommendation"
  subscription_value: "$2K/year for unlimited guidance"

timeline:
  week_1: "S1 Rapid Discovery (Oct 31 - Nov 6)"
  week_2: "S2 Comprehensive (Nov 7 - Nov 13)"
  week_3: "S3 Need-Driven (Nov 14 - Nov 20)"
  week_4: "S4 Strategic (Nov 21 - Nov 27)"
  total_time: "4 weeks, 40-60 hours"

notes:
  - "Triggered by real CFO need (Post 2), not speculative"
  - "High-risk domain (payroll errors cause lawsuits)"
  - "Complex integration requirements (30+ integration points)"
  - "First HRIS research in spawn-solutions portfolio"
  - "Critical for CFO audience - every company deals with this"

created: "2025-10-31"
updated: "2025-10-31"
version: "1.0"
