published: false
# 3.075: Restaurant Labor Scheduling - Experiment Metadata

experiment:
  id: "3.075"
  title: "Labor Scheduling (Restaurant-Specific)"
  category: "Operations & Business Management"
  tier: 3
  status: "s1_complete"
  started: "2025-11-30"
  completed: null
  discovery_method: "detailed_toc"

trigger:
  source: "Seattle restaurant cost pressure analysis"
  date: "2025-11-24"
  description: "Labor = 30-35% of revenue (largest controllable cost). Seattle minimum wage $20.76/hr makes optimization critical. 5-10% labor reduction = $22K-52K/year."
  validation: "Scheduling optimization reduces labor costs 2-5%, overtime prevention 1-3% additional. Compliance violations $500-5,000/incident (Seattle Secure Scheduling Ordinance)."
  related_research:
    - "3.005: POS Systems (sales data for demand forecasting)"
    - "3.070: Food Service Inventory (complementary cost reduction)"
    - "1.096: Scheduling Libraries (DIY constraint solving with OR-Tools, PuLP)"

scope:
  domain: "Restaurant Labor Scheduling Platforms"
  definition: "SaaS and DIY tools for employee shift scheduling, labor cost optimization, compliance automation, and demand forecasting for restaurants/bars"
  includes:
    - "Employee shift scheduling (7shifts, HotSchedules, When I Work, Deputy)"
    - "Toast ecosystem scheduling (Sling by Toast)"
    - "AI-based demand forecasting (POS data → labor needs)"
    - "Compliance automation (Fair Workweek laws, Seattle Secure Scheduling Ordinance)"
    - "Overtime prevention and break management"
    - "Multi-location centralized scheduling"
    - "Mobile apps for shift swaps, time-off requests"
    - "DIY constraint solving (Google OR-Tools)"
  excludes:
    - "Payroll processing (separate 3.503 HRIS category)"
    - "Time tracking only (scheduling must be included)"
    - "Generic workforce management (must be restaurant-specific or adaptable)"

providers:
  tier_1_saas_popular:
    - name: "7shifts"
      research_depth: "s1_complete"
      rationale: "Market leader, free tier, $0-150/mo, mobile-first, 5-star app"

    - name: "HotSchedules (by Fourth)"
      research_depth: "s1_complete"
      rationale: "Enterprise, AI forecasting, POS integration, compliance automation, custom pricing"

    - name: "When I Work"
      research_depth: "s1_complete"
      rationale: "Budget-friendly, $5/user/mo, simple interface, team communication"

    - name: "Deputy"
      research_depth: "s1_complete"
      rationale: "Compliance-focused, free tier (100 shifts/mo), AI scheduling, $0-4.50/user"

  tier_2_saas_toast_ecosystem:
    - name: "Sling by Toast"
      research_depth: "s1_complete"
      rationale: "Toast POS integration, $1.70-3.40/user/mo, real-time labor cost tracking"

  tier_3_diy_open_source:
    - name: "Google OR-Tools"
      research_depth: "s1_complete"
      rationale: "Free constraint solver, unlimited complexity, Python, DIY development required"

research_questions:
  primary:
    - "SaaS vs DIY - ROI comparison for single vs multi-location?"
    - "What is cost range? (per user, per location)"
    - "Labor cost reduction potential - which platforms deliver 2-5% savings?"
    - "Seattle compliance automation - which platforms enforce Secure Scheduling Ordinance?"
    - "AI forecasting ROI - does POS-integrated demand prediction justify premium pricing?"

  secondary:
    - "Overtime prevention - which platforms catch scheduling conflicts before publication?"
    - "Mobile app quality - which platforms have highest employee adoption?"
    - "Multi-location scalability - centralized vs federated scheduling models?"
    - "POS integration depth - real-time sales data vs batch sync?"
    - "DIY feasibility - OR-Tools implementation cost vs SaaS TCO?"

mpse_stages:
  s1_rapid:
    status: "completed"
    completed_date: "2025-11-30"
    goal: "Platform overviews - 6 solutions (5 SaaS + 1 DIY)"
    providers: 6
    time_actual: "2.5 hours"
    deliverables:
      - "00-SYNTHESIS-quick-recommendations.md"

  s2_comprehensive:
    status: "planned"
    goal: "Feature matrix, TCO (6 scenarios), compliance comparison, AI forecasting benchmarks"

  s3_need_driven:
    status: "planned"
    goal: "6 scenarios - small cafe, single restaurant, multi-location, Seattle compliance, Toast user, DIY tech-savvy"

  s4_strategic:
    status: "planned"
    goal: "Vendor consolidation, Toast ecosystem strategy, compliance law evolution, DIY vs SaaS long-term"

integration_relationships:
  upstream:
    - experiment: "3.005"
      title: "POS Systems"
      relationship: "POS sales data feeds demand forecasting (HotSchedules AI, Sling labor % tracking)"

  parallel:
    - experiment: "3.070"
      title: "Food Service Inventory Management"
      relationship: "Labor (30-35%) + Inventory (25-35%) = 60% of restaurant costs (combined optimization)"

    - experiment: "3.503"
      title: "HRIS / HCM Platforms"
      relationship: "Scheduling → payroll integration (timesheets, hours worked)"

  related_tier1:
    - experiment: "1.096"
      title: "Scheduling Libraries"
      relationship: "DIY alternative - OR-Tools, PuLP for custom constraint solving"

key_findings:
  s1_findings:
    - "6 platforms evaluated: 7shifts ($0-150/mo), HotSchedules (custom, $200-300/mo est), When I Work ($5/user), Deputy ($0-4.50/user), Sling ($1.70-3.40/user), OR-Tools (free)"
    - "ROI: 1,300-2,000% for 2-5% labor cost reduction ($450K labor × 3% = $13,500/year savings)"
    - "Free tiers: 7shifts Comp (20 employees), Deputy Starter (100 shifts/mo)"
    - "Seattle compliance: HotSchedules, Deputy support Secure Scheduling Ordinance automation"
    - "AI forecasting: HotSchedules best-in-class (POS + weather + events)"
    - "Toast integration: Sling native integration lowest cost ($1.70/user)"
    - "DIY option: OR-Tools free but requires $2K-5K Python development"

  expected_s2_s4_findings:
    - "TCO break-even: Free tiers (7shifts, Deputy) best for <20 employees. SaaS $35-150/mo middle tier. Enterprise (HotSchedules) $200-300/mo justified only with AI forecasting ROI."
    - "Compliance ROI: Seattle restaurants save $2K-10K/year avoiding violations (justifies $1,620/year Deputy or $3,600/year HotSchedules)"
    - "Vendor consolidation: Toast acquiring scheduling (Sling), likely to acquire or integrate more deeply. HotSchedules (Fourth) consolidating enterprise market."
    - "DIY feasibility: OR-Tools viable for tech-savvy restaurants, $2K-5K setup + $500-1,500/year maintenance vs $420-3,600/year SaaS"

success_criteria:
  s1_complete: "6 platform profiles, synthesis with decision tree, quick recommendations by scenario"
  s2_complete: "Feature matrix, TCO models (6 scenarios), compliance comparison, AI forecasting benchmarks"
  s3_complete: "6 restaurant scenarios with platform matching, ROI calculations"
  s4_complete: "Vendor viability, Toast ecosystem strategy, compliance law trends"
  full_complete: "Restaurant operator can match (size, budget, POS, compliance needs) → platform shortlist with ROI"

business_value:
  market_size: "Universal need for restaurants with 5+ employees (scheduling complexity threshold)"
  decision_frequency: "Initial selection (year 0), re-evaluate every 2-3 years (pricing, features, vendor changes)"
  annual_spend: "$0-$1,800/year (SaaS, single location) OR $2K-5K one-time (DIY OR-Tools)"
  roi_potential: "Labor cost reduction: $9,000-$13,500/year for $1.5M revenue restaurant (2-3% savings). Compliance: $2K-10K/year violation avoidance."

  hardware_store_application:
    catalog: "6 platform profiles + decision tree + ROI models = generic hardware store catalog (this research)"
    application: "Restaurant context (size, POS, location, budget) → platform shortlist (separate applications/ folder)"
    value: "Catalog is timeless; application is context-specific"

created: "2025-11-30"
updated: "2025-11-30"
version: "1.0"

data_sources:
  pricing_data:
    source: "official_pricing_pages"
    accessed: "2025-11-30"
    notes: "7shifts, When I Work, Deputy, Sling public pricing. HotSchedules custom (no public pricing)."

  feature_comparisons:
    source: "official_documentation + vendor_reviews"
    accessed: "2025-11-30"

legal_review:
  tos_compliance: "verified"
  copyright_cleared: true

publication_clearance:
  can_publish_publicly: false
  safe_for_subscribers: true
  requires_disclaimer: true

token_usage:
  breakdown:
    s1_rapid: 13000  # Approximate
