id: "3.023"
title: "Team Chat & Collaboration Platforms"
tier: 3
category: "Communication Infrastructure"
status: "S1-S4 complete"
published: false
created: "2025-12-22"
updated: "2025-12-22"

discovery:
  S1_rapid: "complete"
  S2_comprehensive: "complete"
  S3_need_driven: "complete"
  S4_strategic: "complete"

providers_analyzed:
  - name: "Slack"
    type: "managed"
    tier: "enterprise"
  - name: "Discord"
    type: "managed"
    tier: "community"
  - name: "Telegram"
    type: "managed"
    tier: "consumer"
  - name: "Matrix"
    type: "self-host"
    tier: "open-protocol"
  - name: "Mattermost"
    type: "self-host"
    tier: "enterprise"
  - name: "Microsoft Teams"
    type: "managed"
    tier: "enterprise"

related_categories:
  - "1.132: Self-hosted collaboration"
  - "1.230-239: Open Social Networks & Protocols"
  - "2.074-079: AI Agent Communication Standards"

key_findings:
  - "Matrix offers best platform independence (open protocol, federation)"
  - "Telegram has best mobile experience and bot API"
  - "Slack has best enterprise features but increasingly gated"
  - "Mattermost provides Slack-compatible self-hosting"
  - "Discord offers best free tier for communities"

trigger: "Vikunja Slack bot - evaluate platform alternatives"

tags:
  - "team-chat"
  - "collaboration"
  - "bot-api"
  - "slack-alternatives"
  - "self-hosted"
